---
name: CI

on:
  pull_request:
    branches: ['main']
  push:
    branches-ignore:  ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: '0.8.4'

    - name: Install requirements
      run: |
        uv sync
        uv add pytest pytest-cov flake8 black

    - name: Run flake8
      run: |
        uv run flake8 --statistics --extend-exclude .venv

    - name: Run black
      run: |
        uv run black --diff .

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Build image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/reminder-aggregator:latest .
