---
name: CI

on:
  pull_request:
    branches: ['main']
  push:
    branches-ignore:  ['main']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: '0.8.4'

    - name: Install requirements
      run: uv sync

    - name: Run ruff check
      run: uv run ruff check --show-fixes

    - name: Run ruff format
      run: uv run ruff format --diff

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Docker
      uses: docker/setup-docker-action@v4

    - name: Build image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/reminder-aggregator:latest .
