---
name: Release

"on":
  release:
    types: [published]

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  build-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.9.2'

      - name: Build package
        run: uv build --no-sources --no-progress

      - name: Upload atifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  release:
    runs-on: ubuntu-latest

    environment: release

    needs: build-package

    steps:
      - name: Download atifacts
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '0.9.2'

      - name: Publish to Test-PyPI
        run: uv publish
        env:
          UV_PUBLISH_URL: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        run: uv publish
